### ISSUE TITLE
Potential Twitch minecraftinstance.json change renders InstanceSync prone to NPE

### ISSUE THREAD

**Issue by noobanidus** [Vazkii/InstanceSync#4]
The most recently minecraftinstance.json as generated on a Windows 10 machine, when transferred to my server, failed to properly sync with InstanceSync reporting a null-pointer-exception related to fileNameOnDisk.

It appears that in my own JSON this field is now known as FileNameOnDisk and gson is case-sensitive, hence the value was discarded and the value stored in fileNameOnDisk was null.

I don't know if this is an overall change to Twitch or whether it's a platform specific one.

Recompiling Instance.java and DownloadManager.java to use the proper capitalisation and injecting them into the jar file in place of the previous class files, then uploading this copy of InstanceSync to my server resolved the issue.

As I'm unsure if the issue is caused by a specific change in schema from Twitch's end, or whether it's a new platform-related issue, I'll attempt to file a PR that includes both variations of the field (or read up on GSON to determine if there's a way to ignore case sensitivity for some fields) and check that both aren't null and use whichever is relevant.

**Comment by NielsPilgaard** [comment]
I am also experiencing this issue, here's the console:

> Done setting up hooks
> Running InstanceSync
> InstanceSync 1.0.2
> Running in C:\Users\Niels\Documents\Curse\Minecraft\Instances\Enigmatica 2 Expert Skyblock\.
> Found minecraftinstance.json file
> Reading minecraftinstance.json
> Instance loaded, has 229 mods
> 
> Downloading any missing mods
> Exception in thread "main" java.lang.NullPointerException
>         at java.io.File.<init>(Unknown Source)
>         at vazkii.instancesync.DownloadManager.downloadAddonIfNeeded(DownloadManager.java:65)
>         at vazkii.instancesync.DownloadManager.downloadInstance(DownloadManager.java:37)
>         at vazkii.instancesync.InstanceSync.main(InstanceSync.java:52)
> Press any key to continue . . .

**Comment by noobanidus** [comment]
@NillerMedDild Can you have a look at your minecraftinstance.json file and tell me if you see exclusively instances of "fileNameOnDisk" or "FileNameOnDisk"? I'm still unsure if this is a global change that they've made or a selective one.

**Comment by NielsPilgaard** [comment]
241 counts of `FileNameOnDisk`, 0 counts of `fileNameOnDisk`.

**Comment by noobanidus** [comment]
I'm still not convinced that it's a complete change to the system entirely... maybe the best option is going to be either supporting both fileNameOnDisk and FileNameOnDisk in the gson, then instead of accessing the variable directly have a function which returns the non-null value.

**Comment by MaxNeedsSnacks** [comment]
I'm also able to reproduce yours and Niller's findings on a profile created ~2 months ago

182 counts of `FileNameOnDisk`, none found for `fileNameOnDisk`, currently still checking whether this also applies to old profiles (I hope I still have some lying around)

EDIT: It seems like PascalCase seems to be the standard for every new profile imported / created, which is weird since the rest of the json uses camelCase

**Comment by noobanidus** [comment]
@MaxNeedsSnacks So it would need `fileNameOnDisk` to support older files, but `FileNameOnDisk` to support newer? Gross.

**Comment by MaxNeedsSnacks** [comment]
It's quite frankly just a really weird change. The minecraftinstance.json files from the packzip files don't have this key, anyway, it seems, but as for the actual, physical instance, this just seems like such an odd change.
